#!/bin/bash
BASE="https://aryaglobalwork.com"
DIR="/Users/elliot/Downloads/asd/aryaglobalwork.com"

# Create directories
mkdir -p "$DIR/wp-content/uploads/2026/01"
mkdir -p "$DIR/wp-content/plugins/sureforms/assets/css/minified"
mkdir -p "$DIR/wp-content/plugins/sureforms/assets/js/minified"
mkdir -p "$DIR/wp-content/plugins/ultimate-addons-for-gutenberg/assets/css"
mkdir -p "$DIR/wp-content/plugins/ultimate-addons-for-gutenberg/assets/js"
mkdir -p "$DIR/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/assets/fonts"
mkdir -p "$DIR/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks"
mkdir -p "$DIR/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/styles"
mkdir -p "$DIR/wp-content/themes/astra/assets/css/minified"
mkdir -p "$DIR/wp-content/themes/astra/assets/js/minified"
mkdir -p "$DIR/wp-includes/css/dist/block-library"
mkdir -p "$DIR/wp-includes/js/dist"
mkdir -p "$DIR/wp-includes/blocks"
mkdir -p "$DIR/wp-includes/js"

# Download all assets
URLS=(
# Images
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_15.55.11_REC-1024x448.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_15.55.11_REC-300x131.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_15.55.11_REC-768x336.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_15.55.11_REC.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_16.09.21_REC-1024x450.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_16.09.21_REC-300x132.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_16.09.21_REC-768x338.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_16.09.21_REC.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_16.22.50_REC-1024x449.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_16.22.50_REC-300x131.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_16.22.50_REC-768x336.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_16.22.50_REC.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_20.33.25_REC-1024x449.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_20.33.25_REC-300x132.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_20.33.25_REC-768x337.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_20.33.25_REC.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_20.33.55_REC-1024x451.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_20.33.55_REC-300x132.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_20.33.55_REC-768x338.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/26.01.2026_20.33.55_REC.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/ach1.svg"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/ach2.svg"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/ach3.svg"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/ach4-1.svg"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/cropped-arya_global_work_logo-removebg-preview-e1769615767235-104x64.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/cropped-arya_global_work_logo-removebg-preview-e1769615767235.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/cropped-cropped-arya-global-work-logo-180x180.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/cropped-cropped-arya-global-work-logo-192x192.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/cropped-cropped-arya-global-work-logo-270x270.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/cropped-cropped-arya-global-work-logo-32x32.png"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/image.webp"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/mission_icon.svg"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/values_icons.svg"
"https://aryaglobalwork.com/wp-content/uploads/2026/01/vision.svg"
# CSS
"https://aryaglobalwork.com/wp-content/plugins/sureforms/assets/css/minified/blocks/default/frontend.min.css"
"https://aryaglobalwork.com/wp-content/plugins/sureforms/assets/css/minified/common.min.css"
"https://aryaglobalwork.com/wp-content/plugins/sureforms/assets/css/minified/deps/intl/intlTelInput.min.css"
"https://aryaglobalwork.com/wp-content/plugins/sureforms/assets/css/minified/deps/tom-select.css"
"https://aryaglobalwork.com/wp-content/plugins/sureforms/assets/css/minified/frontend/form.min.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/assets/css/aos.min.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks/button/style-index.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks/buttons/style-index.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks/container/style-index.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks/content/style-index.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks/counter-child-number/style-index.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks/counter/style-index.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks/list-child-icon/style-index.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks/list-child-item/style-index.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks/list/style-index.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/styles/blocks/common.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/styles/extensions/image-mask.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/styles/extensions/responsive-conditions.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/styles/extensions/responsive-controls.css"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/styles/extensions/z-index.css"
"https://aryaglobalwork.com/wp-content/themes/astra/assets/css/minified/main.min.css"
"https://aryaglobalwork.com/wp-content/themes/astra/assets/css/minified/menu-animation.min.css"
"https://aryaglobalwork.com/wp-includes/blocks/button/style.min.css"
"https://aryaglobalwork.com/wp-includes/blocks/buttons/style.min.css"
"https://aryaglobalwork.com/wp-includes/blocks/columns/style.min.css"
"https://aryaglobalwork.com/wp-includes/blocks/heading/style.min.css"
"https://aryaglobalwork.com/wp-includes/blocks/image/style.min.css"
"https://aryaglobalwork.com/wp-includes/blocks/latest-posts/style.min.css"
"https://aryaglobalwork.com/wp-includes/blocks/media-text/style.min.css"
"https://aryaglobalwork.com/wp-includes/blocks/paragraph/style.min.css"
"https://aryaglobalwork.com/wp-includes/blocks/separator/style.min.css"
"https://aryaglobalwork.com/wp-includes/blocks/table/style.min.css"
"https://aryaglobalwork.com/wp-includes/css/dist/block-library/style.min.css"
# JS
"https://aryaglobalwork.com/wp-content/plugins/astra-sites/inc/lib/onboarding/assets/dist/template-preview/main.js"
"https://aryaglobalwork.com/wp-content/plugins/sureforms/assets/build/formSubmit.js"
"https://aryaglobalwork.com/wp-content/plugins/sureforms/assets/js/minified/blocks/input.min.js"
"https://aryaglobalwork.com/wp-content/plugins/sureforms/assets/js/minified/blocks/phone.min.js"
"https://aryaglobalwork.com/wp-content/plugins/sureforms/assets/js/minified/deps/intl/intlTelInputWithUtils.min.js"
"https://aryaglobalwork.com/wp-content/plugins/sureforms/assets/js/minified/frontend.min.js"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/assets/js/aos.min.js"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/assets/js/modal-script.js"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/assets/js/responsive-videos.js"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks/button/view.js"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/build/blocks/counter/view.js"
"https://aryaglobalwork.com/wp-content/themes/astra/assets/js/minified/frontend.min.js"
"https://aryaglobalwork.com/wp-includes/js/dist/api-fetch.min.js"
"https://aryaglobalwork.com/wp-includes/js/dist/dom-ready.min.js"
"https://aryaglobalwork.com/wp-includes/js/dist/hooks.min.js"
"https://aryaglobalwork.com/wp-includes/js/dist/i18n.min.js"
"https://aryaglobalwork.com/wp-includes/js/dist/url.min.js"
"https://aryaglobalwork.com/wp-includes/js/wp-emoji-loader.min.js"
"https://aryaglobalwork.com/wp-includes/js/wp-emoji-release.min.js"
# Fonts
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/assets/fonts/cardo_normal_400.woff"
"https://aryaglobalwork.com/wp-content/plugins/ultimate-addons-for-gutenberg/spectra-v3/assets/fonts/Inter-VariableFont_slnt,wght.woff"
)

for url in "${URLS[@]}"; do
  # Remove the base URL to get local path
  local_path="${url#$BASE/}"
  local_file="$DIR/$local_path"
  local_dir=$(dirname "$local_file")
  
  if [ ! -d "$local_dir" ]; then
    mkdir -p "$local_dir"
  fi
  
  if [ ! -f "$local_file" ]; then
    echo "Downloading: $local_path"
    curl -s -o "$local_file" "$url" --create-dirs
  fi
done

echo "Done downloading assets!"
